services:
  db:
    image: mysql:8.4
    restart: always
    command: >
      --innodb-buffer-pool-size=64M
      --innodb-log-buffer-size=8M
      --max-connections=20
      --performance-schema=OFF
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"USE $$MYSQL_DATABASE; SELECT 1;\" || exit 1"
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 120s

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    image: ${REGISTRY_HOST}/backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

  react:
    image: ${REGISTRY_HOST}/frontend:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
